language: python
python: "2.7"

sudo: required

services:
  - docker

branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible

  # version checks
  - ansible --version
  - docker --version

  # deps
  - pip install -r requirements_dev.txt

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # start up an elasticsearch node
  - docker run -d -p 127.0.0.1:9200:9200 docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  - for i in {1..6}; do [[ "$(curl -s localhost:9200 | jq .tagline)" == '"You Know, for Search"' ]] && break || echo "waiting on elasticsearch..."; sleep 10; done; ! echo "timeout";

script:
  - python -m pytest
  - ansible-playbook test.yml --syntax-check
    # using block string because it's more readable than escaping quotes
  - |
    ansible-playbook test.yml -vvv -e '{metricbeat_output_elasticsearch_hosts: ["elasticsearch:9200"], metricbeat_setup_run: false}'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
