---
# tasks file for metricbeat
- debug: msg="Starting tasks from metricbeat..."

- name: 'setup debian repo'
  include_tasks: tasks/debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'setup enterprise linux repo'
  include_tasks: tasks/el.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install metricbeat
  package: name=metricbeat

- name: 'enable service'
  service:
    name: metricbeat
    state: stopped
    enabled: yes

- name: 'create config directories'
  file:
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
    path: "{{ item }}"
  with_items:
    - "{{ metricbeat_configs_path }}"
    - "{{ metricbeat_configs_path }}/modules.d"

- name: 'write main config file'
  template:
    dest: "{{ metricbeat_configs_path }}/metricbeat.yml"
    mode: "u=rw,g=r,o=r"
    owner: root
    group: root
    src: templates/metricbeat.j2

- name: 'write only enabled metricbeat module config files'
  template:
    dest: "{{ metricbeat_configs_path }}/modules.d/{{ item }}.yml"
    mode: "u=rw,g=r,o=r"
    owner: root
    group: root
    src: templates/module.j2
  with_items: "{{ metricbeat_module_configs_enabled }}"

- name: 'write disabled metricbeat module config files'
  template:
    dest: "{{ metricbeat_configs_path }}/modules.d/{{ item }}.yml.disabled"
    mode: "u=rw,g=r,o=r"
    owner: root
    group: root
    src: templates/module.j2
  with_items: "{{ metricbeat_module_configs }}"
  when: 
    - metricbeat_module_configs_write_disabled
    - item not in metricbeat_module_configs_enabled

- name: 'check for metricbeat.sh'
  stat:
    path: /usr/bin/metricbeat.sh
  register: stat_script

- name: 'symlink metricbeat.sh if necessary'
  file:
    state: link
    mode: "u=rwx,g=rx,o=rx"
    owner: root
    group: root
    src: /usr/bin/metricbeat.sh
    dest: /usr/bin/metricbeat
  when: stat_script.stat.exists

- name: 'creating metricbeat indexes and dashboards'
  shell: metricbeat setup
  when:
    - metricbeat_setup_run